# Paste this into Streamlit Cloud → Settings → Secrets
SUPABASE_URL = "https://YOUR-PROJECT.supabase.co"
SUPABASE_KEY = "YOUR_SERVICE_ROLE_OR_ANON_KEY"
SUPABASE_BUCKET = "uitm-files"
SITE_SALT = "Okt2025"
